In [2]:
print("hello")

hello


In [3]:
a=10
b=20
print(a*b)

200


In [4]:
a=20
b=30
print(b+a)

50


In [6]:
a=40
b=60
a+b
input("enter")

'49'

In [7]:
import numpy

In [8]:
import numpy as np

In [12]:
arr1=np.array([1,4,7,9,5])
arr1*4
arr1[2:4]=[30,50] 
arr1


array([ 1,  4, 30, 50,  5])

In [16]:
arr1=[2,5,4,3,6,7,9]
arr1[5]=50
arr1.ndim


[2, 5, 4, 3, 6, 50, 9]

In [9]:
arr1.ndim

AttributeError: 'tuple' object has no attribute 'ndim'

In [13]:
arr1=np.array([1,3,4,4,5,6])


In [14]:
arr1.shape

(6,)

In [15]:
arr1.ndim

1

In [18]:
arr1[:]=10
arr1

array([10, 10, 10, 10, 10, 10])

In [29]:
arr2=np.array([[1,2,3,4,5],[1,1,4,5,7],[2,4,5,7,9]])
arr2.shape
arr2.size
arr2.dtype
arr2

array([[1, 2, 3, 4, 5],
       [1, 1, 4, 5, 7],
       [2, 4, 5, 7, 9]])

In [22]:
arr2.size

15

In [23]:
arr2.shape

(3, 5)

In [24]:
arr2.ndim

2

In [28]:
arr2[2,1]=10
arr2

array([[ 1,  2,  3,  4,  5],
       [ 1,  1,  4,  5,  7],
       [ 2, 10,  5,  7,  9]])

In [33]:
arr2[:,2]=[1,2,3]
arr2

array([[1, 2, 1, 4, 5],
       [1, 1, 2, 5, 7],
       [2, 4, 3, 7, 9]])

In [35]:
arr2[:,2]=4
arr2

array([[1, 2, 4, 4, 5],
       [1, 1, 4, 5, 7],
       [2, 4, 4, 7, 9]])

In [36]:
arr2[2,3]=0
arr2

array([[1, 2, 4, 4, 5],
       [1, 1, 4, 5, 7],
       [2, 4, 4, 0, 9]])

In [55]:
arr2[0:2][2:2]=9
arr2

array([[1, 2, 4, 0, 5],
       [1, 1, 4, 0, 7],
       [2, 4, 4, 0, 9]])

In [108]:
arr3=np.array([[14,56,68],[38,66,78],[42,66,78],[84,76,32],[23,56,78],[66,58,70],[50,58,34]])
arr3

array([[14, 56, 68],
       [38, 66, 78],
       [42, 66, 78],
       [84, 76, 32],
       [23, 56, 78],
       [66, 58, 70],
       [50, 58, 34]])

In [49]:
arr3.shape

(7, 3)

In [67]:
arr3[:,::2]

array([[14, 68],
       [38, 78],
       [42, 78],
       [84, 32],
       [23, 78],
       [66, 70],
       [50, 34]])

In [88]:
arr3

array([[14, 56, 68],
       [38, 66, 78],
       [42, 66, 78],
       [84, 76, 32],
       [23, 56, 78],
       [66, 58, 70],
       [50, 58, 34]])

In [85]:
arr3[:6:]=7
arr3

array([[ 7,  7,  7],
       [ 7,  7,  7],
       [ 7,  7,  7],
       [ 7,  7,  7],
       [ 7,  7,  7],
       [ 7,  7,  7],
       [50, 58, 34]])

In [130]:
arr2[[0:6][0:2]]=0
arr2


SyntaxError: invalid syntax (1182938993.py, line 1)

In [107]:
arr3

array([[-1, 56, -1],
       [38, 66, 78],
       [-1, 66, 78],
       [84, 76, 32],
       [23, 56, 78],
       [66, 58, 70],
       [-1, 58, -1]])

In [110]:
arr3[-1,-3]=-1
arr3[-1,-1]=-1
arr3[0,0]=-1
arr3[0,2]=-1

In [111]:
arr3

array([[-1, 56, -1],
       [38, 66, 78],
       [42, 66, 78],
       [84, 76, 32],
       [23, 56, 78],
       [66, 58, 70],
       [-1, 58, -1]])

In [113]:
arr3[[0,1,6],[1,1,1]]

array([56, 66, 58])

In [29]:
arr3[[3,4,6],[2,1,1]]=[1,4,8]

NameError: name 'arr3' is not defined

In [120]:
arr3

array([[-1, 56, -1],
       [38, 66, 78],
       [42, 66, 78],
       [84, 76,  1],
       [23,  4, 78],
       [66, 58, 70],
       [-1,  8, -1]])

In [143]:
arr4=np.random.randint(1,100,(7,3))
arr4

array([[ 8, 98, 31],
       [32,  6, 85],
       [30, 63, 82],
       [37, 27,  3],
       [31,  1, 98],
       [21, 49, 25],
       [77, 82, 85]])

In [131]:
arr4[[0,1,4]]=255
arr4

array([[255, 255, 255],
       [255, 255, 255],
       [ 48,  82,  18],
       [ 56,  34,  98],
       [255, 255, 255],
       [ 23,  25,  95],
       [ 25,  28,  69]])

In [134]:
arr4[:,:2]=8

In [141]:
arr4[arr4>50]=0
arr4

array([[35,  0,  0],
       [ 6,  0,  0],
       [ 0, 16, 35],
       [ 0, 18, 11],
       [ 0,  0,  0],
       [ 0,  0, 37],
       [26,  0,  0]])

In [144]:
arr4[arr4%2==0]

array([ 8, 98, 32,  6, 30, 82, 98, 82])

In [2]:
arr[arr>30]

array([45, 34, 90, 55, 63])

In [ ]:
import numpy as np  
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])
arr[arr>30]
arr[arr%2!=0]
arr[arr%5==0]=-1
arr
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])
sum(arr<50)

In [3]:
arr[arr%5==0]=-1

In [4]:
arr

array([12, -1,  7, 19, 34, 28, -1, -1, 63])

In [5]:
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])

In [6]:
sum(arr<50)

6

In [7]:
arr

array([12, 45,  7, 19, 34, 28, 90, 55, 63])

In [16]:
arr = np.array([[10, 25, 40],  
                [55, 18, 72],  
                [91, 30, 64]])


In [10]:
arr[arr>50]
arr

array([[10, 25, 40],
       [55, 18, 72],
       [91, 30, 64]])

In [11]:
arr[arr>50]

array([55, 72, 91, 64])

In [12]:
arr[arr%2==0]

array([10, 40, 18, 72, 30, 64])

In [14]:
arr[arr%2==0]=0
arr

array([[ 0, 25,  0],
       [55,  0,  0],
       [91,  0,  0]])

In [19]:
arr[arr%5==0]

array([10, 25, 40, 55, 30])

In [51]:
arr[(arr>20)& (arr<70)]

array([34, 56, 23, 45, 67])

In [34]:
arr = np.array([[12, 34, 56],  
                [78, 90, 23],  
                [45, 67, 89]])


In [49]:
arr[[::],[::]]

SyntaxError: invalid syntax (1826959949.py, line 1)

In [37]:
arr[[0,1,2],[0,1,1]]

array([12, 90, 67])

In [44]:
arr[[0,2]]=arr[[2,0]]
arr

array([[12, 34, 56],
       [78, 90, 23],
       [45, 67, 89]])

In [40]:
arr1=arr[[2,1,0],:]
arr1

array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [45]:
np.sum(arr>50)

5

In [46]:
len(arr>50)

3

In [47]:
sum(arr>50)

array([1, 2, 2])

In [52]:
arr = np.array([[5, 15, 25],  
                [35, 45, 55],  
                [65, 75, 85]])



In [56]:
arr[arr>60]*=2
arr

array([[  5,  15,  25],
       [ 35,  45,  55],
       [260, 300, 340]])

In [59]:
arr[::,2]=100
arr

array([[  5,  15, 100],
       [ 35,  45, 100],
       [260, 300, 100]])

In [60]:
np.sum(arr,axis=1)

array([120, 180, 660])

In [61]:
np.sum(arr,axis=0)

array([300, 360, 300])

In [62]:
np.min(arr,axis=1)

array([  5,  35, 100])

In [63]:
np.max(arr,axis=0)

array([260, 300, 100])

In [64]:
np.mean(arr,axis=1)

array([ 40.,  60., 220.])

In [65]:
np.median(arr,axis=1)

array([ 15.,  45., 260.])

In [68]:
np.std(arr,axis=1)

array([42.62237284, 28.57738033, 86.40987598])

In [76]:
np.argmax(arr,axis=0)

array([2, 2, 0], dtype=int64)

In [81]:
np.var(arr,axis=0)



array([12950., 16350.,     0.])

In [78]:
np.argmax(arr)
arr

array([[  5,  15, 100],
       [ 35,  45, 100],
       [260, 300, 100]])

In [83]:
np.zeros((10,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [84]:
np.ones((10,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [103]:
arr=np.full((4,8),6)

In [93]:
np.full_like(arr,1)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [110]:
b=np.arange(100,0,-1)

In [113]:
b.size
np.reshape(b,(20,5))


array([[100,  99,  98,  97,  96],
       [ 95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86],
       [ 85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76],
       [ 75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66],
       [ 65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56],
       [ 55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46],
       [ 45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36],
       [ 35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26],
       [ 25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16],
       [ 15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6],
       [  5,   4,   3,   2,   1]])

In [118]:
np.random.randint(1,1000,(20,5))

array([[169, 290, 748, 747, 372],
       [756, 577, 352, 877,  65],
       [331, 581, 783,  85, 250],
       [647, 863, 537, 656, 607],
       [ 32, 201, 276, 366, 780],
       [182, 701, 897, 741, 363],
       [228, 915,  69, 347, 726],
       [239, 985, 355,  45, 386],
       [456,  30, 207, 746,  29],
       [181, 690, 199, 275, 210],
       [ 37, 613, 138, 679, 360],
       [ 83, 703, 186, 267, 783],
       [241, 849,  63, 257, 176],
       [478, 268, 654, 227, 639],
       [587, 589, 607, 593, 148],
       [434, 151,  31, 872, 567],
       [896, 295, 938, 418,  71],
       [223, 309, 421, 998,  90],
       [ 67, 186, 499, 630, 870],
       [841,  50, 650, 578, 185]])

In [126]:
np.random.randint(1,3,(10,5))

array([[2, 1, 1, 2, 1],
       [2, 2, 1, 2, 2],
       [2, 1, 1, 1, 2],
       [1, 2, 2, 1, 1],
       [1, 2, 2, 2, 2],
       [2, 1, 1, 1, 1],
       [1, 1, 1, 2, 2],
       [1, 1, 1, 2, 2],
       [2, 2, 2, 1, 2],
       [2, 2, 1, 2, 1]])

In [127]:
np.random.random()

0.821285300494715

In [ ]:
()

In [117]:
np.reshape(b,(9,1))

ValueError: cannot reshape array of size 100 into shape (9,1)